import { inject, Injectable, signal } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Router } from '@angular/router';
import { ToastService } from './toast.service';

export interface UserProfile {
  id?: string; // auto-generated by json-server (optional)
  userId: string; // Firebase user localId
  firstName: string;
  lastName: string;
  foodPreferences: string[];
}

@Injectable({
  providedIn: 'root',
})
export class ProfileService {
  private readonly http = inject(HttpClient);
  private readonly router = inject(Router);
  private readonly toastService = inject(ToastService);
  private readonly baseUrl = 'http://localhost:3000/profiles';

  readonly currentProfile = signal<UserProfile | null>(null);

  loadProfile(userId: string): void {
    if (!userId) return;
    // Query by userId field to bypass json-server ID auto-generation quirks
    this.http.get<UserProfile[]>(`${this.baseUrl}?userId=${userId}`).subscribe({
      next: (profiles) => {
        if (profiles && profiles.length > 0) {
          this.currentProfile.set(profiles[0]);
        } else {
          this.currentProfile.set({
            userId: userId,
            firstName: '',
            lastName: '',
            foodPreferences: [],
          });
        }
      },
      error: () => {
        this.currentProfile.set({
          userId: userId,
          firstName: '',
          lastName: '',
          foodPreferences: [],
        });
      },
    });
  }

  saveProfile(profile: UserProfile): void {
    this.http.get<UserProfile[]>(`${this.baseUrl}?userId=${profile.userId}`).subscribe({
      next: (profiles) => {
        if (profiles && profiles.length > 0) {
          // Exists, PUT using the exact auto-generated database id of the record
          const existingProfile = profiles[0];
          const updatedProfile = { ...profile, id: existingProfile.id };
          this.http.put<UserProfile>(`${this.baseUrl}/${existingProfile.id}`, updatedProfile).subscribe({
            next: (saved) => {
              this.currentProfile.set(saved);
              this.toastService.show('Profile updated successfully!', 'success');
              this.router.navigate(['/recipes']);
            },
            error: () => this.toastService.show('Failed to save profile.', 'error'),
          });
        } else {
          // Does not exist, POST
          const { id, ...postData } = profile;
          this.http.post<UserProfile>(this.baseUrl, postData).subscribe({
            next: (saved) => {
              this.currentProfile.set(saved);
              this.toastService.show('Profile created successfully!', 'success');
              this.router.navigate(['/recipes']);
            },
            error: () => this.toastService.show('Failed to create profile.', 'error'),
          });
        }
      },
      error: () => this.toastService.show('Failed to verify profile status.', 'error'),
    });
  }
}
