import { inject, Injectable, signal } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Router } from '@angular/router';
import { ToastService } from './toast.service';
import { environment } from '../../environments/environment';
import { catchError, map, switchMap } from 'rxjs';

export interface UserProfile {
  id?: string; // auto-generated by json-server (optional)
  userId: string; // Firebase user localId
  firstName: string;
  lastName: string;
  foodPreferences: string[];
}

@Injectable({
  providedIn: 'root',
})
export class ProfileService {
  private readonly http = inject(HttpClient);
  private readonly router = inject(Router);
  private readonly toastService = inject(ToastService);
  private readonly baseUrl = `${environment.apiBaseUrl}/profiles`;

  readonly currentProfile = signal<UserProfile | null>(null);

  private createEmptyProfile(userId: string): UserProfile {
    return {
      userId,
      firstName: '',
      lastName: '',
      foodPreferences: [],
    };
  }

  private handleSaveSuccess(saved: UserProfile, message: string): void {
    this.currentProfile.set(saved);
    this.toastService.show(message, 'success');
    this.router.navigate(['/recipes']);
  }

  loadProfile(userId: string): void {
    if (!userId) return;
    // Query by userId field to bypass json-server ID auto-generation quirks
    this.http.get<UserProfile[]>(`${this.baseUrl}?userId=${userId}`).subscribe({
      next: (profiles) => {
        const profile = profiles && profiles.length > 0 ? profiles[0] : this.createEmptyProfile(userId);
        this.currentProfile.set(profile);
      },
      error: () => {
        this.currentProfile.set(this.createEmptyProfile(userId));
      },
    });
  }

  saveProfile(profile: UserProfile): void {
    this.http.get<UserProfile[]>(`${this.baseUrl}?userId=${profile.userId}`).pipe(
      catchError((err) => {
        this.toastService.show('Failed to verify profile status.', 'error');
        throw err;
      }),
      switchMap((profiles) => {
        if (profiles && profiles.length > 0) {
          // Exists, PUT using the exact auto-generated database id of the record
          const existingProfile = profiles[0];
          const updatedProfile = { ...profile, id: existingProfile.id };
          return this.http.put<UserProfile>(`${this.baseUrl}/${existingProfile.id}`, updatedProfile).pipe(
            map((saved) => ({ saved, isNew: false })),
            catchError((err) => {
              this.toastService.show('Failed to save profile.', 'error');
              throw err;
            })
          );
        } else {
          // Does not exist, POST
          const { id, ...postData } = profile;
          return this.http.post<UserProfile>(this.baseUrl, postData).pipe(
            map((saved) => ({ saved, isNew: true })),
            catchError((err) => {
              this.toastService.show('Failed to create profile.', 'error');
              throw err;
            })
          );
        }
      })
    ).subscribe({
      next: ({ saved, isNew }) => {
        const message = isNew ? 'Profile created successfully!' : 'Profile updated successfully!';
        this.handleSaveSuccess(saved, message);
      },
      error: () => {
        // Errors are already handled and toasted inside pipe catchError blocks
      },
    });
  }
}
